"""SystemVerilog emission for zero-runtime-weight-fetch mat-vec cores."""

from __future__ import annotations

import re

from .ir import Atom, CompilationPlan, ValueRef


def sanitize_identifier(value: str) -> str:
    identifier = re.sub(r"[^a-zA-Z0-9_$]", "_", value)
    if not identifier or identifier[0].isdigit():
        identifier = f"h_{identifier}"
    return identifier


def _atom_name(atom: Atom) -> str:
    sign = "p" if atom.sign > 0 else "n"
    return f"a_i{atom.input_index}_s{atom.shift}_{sign}"


def _ref_name(ref: ValueRef) -> str:
    if isinstance(ref, Atom):
        return _atom_name(ref)
    return f"n_{ref.node_id:06d}"


def emit_systemverilog(plan: CompilationPlan, *, module_name: str) -> str:
    """Emit a fixed-shape, flattened-port combinational SystemVerilog module."""

    module = sanitize_identifier(module_name)
    in_bus_width = plan.input_count * plan.input_width
    out_bus_width = plan.output_count * plan.accumulator_width
    extension = plan.accumulator_width - plan.input_width

    atoms: set[Atom] = set()
    for node in plan.nodes:
        if isinstance(node.lhs, Atom):
            atoms.add(node.lhs)
        if isinstance(node.rhs, Atom):
            atoms.add(node.rhs)
    for output in plan.outputs:
        if isinstance(output, Atom):
            atoms.add(output)

    lines = [
        "// Generated by Hephaestus. The coefficient matrix is encoded in logic topology.",
        "// Runtime weight reads per matrix-vector operation: 0.",
        f"module {module} (",
        f"    input  wire signed [{in_bus_width - 1}:0] x_flat,",
        f"    output wire signed [{out_bus_width - 1}:0] y_flat",
        ");",
        "",
        f"  localparam integer INPUT_COUNT = {plan.input_count};",
        f"  localparam integer OUTPUT_COUNT = {plan.output_count};",
        f"  localparam integer INPUT_WIDTH = {plan.input_width};",
        f"  localparam integer ACC_WIDTH = {plan.accumulator_width};",
        "",
    ]

    for index in range(plan.input_count):
        lines.extend(
            [
                f"  wire signed [{plan.input_width - 1}:0] x_{index};",
                f"  wire signed [{plan.accumulator_width - 1}:0] sx_{index};",
                f"  assign x_{index} = x_flat[{index * plan.input_width} +: INPUT_WIDTH];",
            ]
        )
        if extension == 0:
            lines.append(f"  assign sx_{index} = x_{index};")
        else:
            lines.append(
                f"  assign sx_{index} = {{{{{extension}{{x_{index}[INPUT_WIDTH-1]}}}}, x_{index}}};"
            )
    lines.append("")

    for atom in sorted(atoms):
        source = f"(sx_{atom.input_index} <<< {atom.shift})"
        expression = source if atom.sign > 0 else f"-{source}"
        lines.extend(
            [
                f"  wire signed [{plan.accumulator_width - 1}:0] {_atom_name(atom)};",
                f"  assign {_atom_name(atom)} = {expression};",
            ]
        )
    if atoms:
        lines.append("")

    for node in plan.nodes:
        lines.extend(
            [
                f"  wire signed [{plan.accumulator_width - 1}:0] n_{node.node_id:06d};",
                (f"  assign n_{node.node_id:06d} = {_ref_name(node.lhs)} + {_ref_name(node.rhs)};"),
            ]
        )
    if plan.nodes:
        lines.append("")

    for output_index, output in enumerate(plan.outputs):
        expression = "{ACC_WIDTH{1'b0}}" if output is None else _ref_name(output)
        lines.append(
            f"  assign y_flat[{output_index * plan.accumulator_width} +: ACC_WIDTH] = {expression};"
        )

    lines.extend(["", "endmodule", ""])
    return "\n".join(lines)
