"""Same-run provenance checks for the public routed PVT evidence API."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ._common import (
    PVTCornerError,
    load_json,
    require_string,
    resolve_input_directory,
    resolve_under,
    sha256_file,
)

_POST_SCHEMA = "hephaestus.post-physical-equivalence-evidence.v1"
_POST_LEVEL = "exact_registered_source_to_routed_sequential_equivalence"
_PHYSICAL_WORKFLOW_FRAGMENT = "/.github/workflows/openroad-physical-evidence.yml@"


def _positive_run_id(value: Any, *, context: str) -> str:
    text = require_string(value, context=context)
    if not text.isdigit() or int(text) <= 0:
        raise PVTCornerError(f"{context} must be a positive integer")
    return text


def validate_upstream_run_binding(
    post_physical_root: str | Path,
    upstream_run_id: str | None,
) -> dict[str, str] | None:
    """Bind a supplied upstream run ID to the post-physical artifact itself.

    Local exploratory callers may omit ``upstream_run_id``. A caller that records
    a run ID must prove that the exact post-physical manifest was generated by
    that same GitHub Actions run and by the permanent physical workflow.
    """

    if upstream_run_id is None:
        return None
    expected = _positive_run_id(
        upstream_run_id,
        context="upstream physical workflow run ID",
    )
    root = resolve_input_directory(
        Path(post_physical_root),
        context="post-physical evidence artifact",
    )
    manifest_path = resolve_under(
        root,
        "post_physical_equivalence_evidence.json",
        context="post-physical evidence manifest",
    )
    manifest = load_json(manifest_path)
    if manifest.get("schema") != _POST_SCHEMA:
        raise PVTCornerError("unsupported post-physical evidence schema")
    if manifest.get("evidence_level") != _POST_LEVEL:
        raise PVTCornerError("unexpected post-physical evidence level")
    execution = manifest.get("execution")
    if not isinstance(execution, dict):
        raise PVTCornerError("post-physical execution provenance is malformed")
    actual = _positive_run_id(
        execution.get("github_run_id"),
        context="post-physical GitHub workflow run ID",
    )
    if actual != expected:
        raise PVTCornerError(
            "post-physical artifact came from another workflow run: "
            f"expected {expected}, got {actual}"
        )
    workflow_ref = require_string(
        execution.get("github_workflow_ref"),
        context="post-physical GitHub workflow ref",
    )
    if _PHYSICAL_WORKFLOW_FRAGMENT not in workflow_ref:
        raise PVTCornerError(
            "post-physical artifact was not generated by the permanent physical workflow"
        )
    return {
        "upstream_physical_workflow_run_id": actual,
        "post_physical_manifest_sha256": sha256_file(manifest_path),
        "post_physical_workflow_ref": workflow_ref,
    }
